# Generated by Django 6.0.5 on 2026-06-07 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agencies.agency'),
        ),
    ]
