# Generated by Django 6.0.5 on 2026-08-26 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_alter_agency_options_agency_email_agency_is_active_and_more'),
        ('inventory', '0001_initial'),
        ('products', '0003_product_agency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('agency', 'product')},
        ),
    ]
