# Generated by Django 6.0.5 on 2026-07-10 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('products', '0002_alter_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agencies.agency'),
        ),
    ]
